### ISSUE TITLE
Game crashes when entering South Harbor

### ISSUE THREAD

**Issue by SupremeDevice** [fauxless/crosscode-ninja-skin-rework#2]
Exactly as title sounds. With mod enabled through CCLoader, trying to enter the South Harbor room in Rookie Harbor causes a crash. Happens whether you try to enter from the north or the south entrance, or loading into the South Harbor from the autosave it generates right before the crash. 
Disabling the mod and restarting the game fixes the issue.
Having the DLC ninja skip equipped through the inventory menu does not make a difference.

This is the error the game prints out:
[crosscode crash.txt](https://github.com/fauxless/crosscode-ninja-skin-rework/files/9365946/crosscode.crash.txt)

For what it's worth, my progress in the game is right after completing the Faj'ro Temple.

**Comment by fauxless** [comment]
Hey, thanks for bringing this up! I think I might have an idea as to what's causing this. I'll take a look.

**Comment by fauxless** [comment]
I've done some small tweaking to the code in that area in the new release. Let me know if it's still giving you trouble.

**Comment by SupremeDevice** [comment]
Unfortunately, the latest release does not fix the crash.
Tried with both simply overwriting the old mod files and doing a clean install of the mod.

Here's the error this time, haven't checked if it's any different though.
[crosscode crash two.txt](https://github.com/fauxless/crosscode-ninja-skin-rework/files/9377935/crosscode.crash.two.txt)

**Comment by fauxless** [comment]
Damn, that sucks. I'll take a look at it again.

In the meantime, you can probably fix this problem by going here in the mod:
/assets/data/maps/rookie-harbor/
and deleting the file 'south.json.'

That'll eliminate any changes I made to that area in the map and reset it to its vanilla state while keeping the rest of the mod intact. I'll work on fixing this though.

**Comment by JosEffigy** [comment]
Probably should put the warning in the modpage that it changes some map files.
